version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gilangr
      POSTGRES_PASSWORD: gilang
      POSTGRES_DB: rails_dd_development
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://gilangr:gilang@db:5432/rails_dd_development
      - RAILS_ENV=development

volumes:
  postgres_data:
